# Generated by Django 4.1.3 on 2022-11-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('discount_percentage', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
    ]
